# Generated by Django 5.2.1 on 2026-04-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_release_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['release_year', 'title_en']},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='movie',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_ru',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
